//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vista {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EspañolMain {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EspañolMain() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vista.EspañolMain", typeof(EspañolMain).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultas.
        /// </summary>
        internal static string btnConsultas {
            get {
                return ResourceManager.GetString("btnConsultas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empleados.
        /// </summary>
        internal static string btnEmpleados {
            get {
                return ResourceManager.GetString("btnEmpleados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expediente.
        /// </summary>
        internal static string btnExpediente {
            get {
                return ResourceManager.GetString("btnExpediente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factura.
        /// </summary>
        internal static string btnFactura {
            get {
                return ResourceManager.GetString("btnFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perros.
        /// </summary>
        internal static string btnPerros {
            get {
                return ResourceManager.GetString("btnPerros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propietarios.
        /// </summary>
        internal static string btnPropietarios {
            get {
                return ResourceManager.GetString("btnPropietarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        internal static string btnUsuario {
            get {
                return ResourceManager.GetString("btnUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string chkTraducirMain {
            get {
                return ResourceManager.GetString("chkTraducirMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajustes.
        /// </summary>
        internal static string grbAjustes {
            get {
                return ResourceManager.GetString("grbAjustes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenidos a:.
        /// </summary>
        internal static string lblBienvenidos {
            get {
                return ResourceManager.GetString("lblBienvenidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar
        ///contraseña.
        /// </summary>
        internal static string lblCambiarContra {
            get {
                return ResourceManager.GetString("lblCambiarContra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargo:.
        /// </summary>
        internal static string lblCargo {
            get {
                return ResourceManager.GetString("lblCargo", resourceCulture);
            }
        }
    }
}
