//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vista {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EspañolPrimerUso {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EspañolPrimerUso() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vista.EspañolPrimerUso", typeof(EspañolPrimerUso).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceder.
        /// </summary>
        internal static string btnPrimerUso {
            get {
                return ResourceManager.GetString("btnPrimerUso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presiona el boton de acceder al primer uso.
        /// </summary>
        internal static string lblAccederPrimerUso {
            get {
                return ResourceManager.GetString("lblAccederPrimerUso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para ponerte en contexto, el sistema no ha detectado a ningún usuario registrado actualmente, entonces
        ///tú tendrás la misión de registrar al primer empleado, luego al primer usuario. Más adelante se te irá
        ///explicando..
        /// </summary>
        internal static string lblContextoPrimerUso {
            get {
                return ResourceManager.GetString("lblContextoPrimerUso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hola!, Bienvenido al Sistema administrado de veterinaria, en el podrás como se menciona anteiormente
        ///administrar la infomación de una veterinaria, de una manera general..
        /// </summary>
        internal static string lblHolaPrimerUso {
            get {
                return ResourceManager.GetString("lblHolaPrimerUso", resourceCulture);
            }
        }
    }
}
