//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vista {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InglesPrimerUso {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InglesPrimerUso() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vista.InglesPrimerUso", typeof(InglesPrimerUso).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add username.
        /// </summary>
        internal static string btnAgregarUsuarioPrimerUsu {
            get {
                return ResourceManager.GetString("btnAgregarUsuarioPrimerUsu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To access.
        /// </summary>
        internal static string btnPrimerUso {
            get {
                return ResourceManager.GetString("btnPrimerUso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register contact.
        /// </summary>
        internal static string chkContacto {
            get {
                return ResourceManager.GetString("chkContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New user data.
        /// </summary>
        internal static string grbDatosNuevoUsuario {
            get {
                return ResourceManager.GetString("grbDatosNuevoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the button to access the first use.
        /// </summary>
        internal static string lblAccederPrimerUso {
            get {
                return ResourceManager.GetString("lblAccederPrimerUso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add
        ///data.
        /// </summary>
        internal static string lblAgregarDatosNuevoEmp {
            get {
                return ResourceManager.GetString("lblAgregarDatosNuevoEmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last names:.
        /// </summary>
        internal static string lblApellidosNuevoEmp {
            get {
                return ResourceManager.GetString("lblApellidosNuevoEmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To put you in context, the system has not detected any currently registered user, so 
        ///you will have the mission of registering the first employee, then the first user. Later it will be explained to you..
        /// </summary>
        internal static string lblContextoPrimerUso {
            get {
                return ResourceManager.GetString("lblContextoPrimerUso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adress gmail:.
        /// </summary>
        internal static string lblCorreoNuevoUsu {
            get {
                return ResourceManager.GetString("lblCorreoNuevoUsu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New employee data.
        /// </summary>
        internal static string lblDatosNuevoEmp {
            get {
                return ResourceManager.GetString("lblDatosNuevoEmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departament:.
        /// </summary>
        internal static string lblDepartamentoNuevoEmp {
            get {
                return ResourceManager.GetString("lblDepartamentoNuevoEmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi! Welcome to the veterinary administrator system, in which you can manage the 
        ///information of a veterinary, in a general way..
        /// </summary>
        internal static string lblHolaPrimerUso {
            get {
                return ResourceManager.GetString("lblHolaPrimerUso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello again, as you just entered the first employee, now what continues is to 
        ///add the first user with that would be enough, so you can start to see the system and use it..
        /// </summary>
        internal static string lblHolaPrimerUsuario {
            get {
                return ResourceManager.GetString("lblHolaPrimerUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At the moment there is no employee, so you are in charge of registering the first employee, and then creating him
        ///a user and later we will continue to explain the process you must follow to finish configuring the system
        ///and be able to use it without any intervention.
        /// </summary>
        internal static string lblInfoRegistrarEmp {
            get {
                return ResourceManager.GetString("lblInfoRegistrarEmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipality:.
        /// </summary>
        internal static string lblMunicipioNuevoEmp {
            get {
                return ResourceManager.GetString("lblMunicipioNuevoEmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth:.
        /// </summary>
        internal static string lblNacimientoNuevoEmp {
            get {
                return ResourceManager.GetString("lblNacimientoNuevoEmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Names:.
        /// </summary>
        internal static string lblNombreNuevoEmp {
            get {
                return ResourceManager.GetString("lblNombreNuevoEmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        internal static string lblNombreNuevoUsu {
            get {
                return ResourceManager.GetString("lblNombreNuevoUsu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document number:.
        /// </summary>
        internal static string lblNumDocNuevoEmp {
            get {
                return ResourceManager.GetString("lblNumDocNuevoEmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of contact:.
        /// </summary>
        internal static string lblNumTelsNuevoEmp {
            get {
                return ResourceManager.GetString("lblNumTelsNuevoEmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first employee you sign up will have to be a manager.
        /// </summary>
        internal static string lblRegistrarEmp {
            get {
                return ResourceManager.GetString("lblRegistrarEmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember that this user will be a manager capable
        /// of having all the administration functions.
        ///This user user will have a default password that is &quot;NewPassword123&quot;.
        ///Please fill in all the fields that the form asks for..
        /// </summary>
        internal static string lblReglasPrimerUsuario {
            get {
                return ResourceManager.GetString("lblReglasPrimerUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the employee you are.
        /// </summary>
        internal static string lblSelecEmpleados {
            get {
                return ResourceManager.GetString("lblSelecEmpleados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document type:.
        /// </summary>
        internal static string lblTipoDocNuevoEmp {
            get {
                return ResourceManager.GetString("lblTipoDocNuevoEmp", resourceCulture);
            }
        }
    }
}
