//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vista {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InglesUsuario {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InglesUsuario() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vista.InglesUsuario", typeof(InglesUsuario).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Buscar {
            get {
                return ResourceManager.GetString("Buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data:.
        /// </summary>
        internal static string grpdatos {
            get {
                return ResourceManager.GetString("grpdatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update
        ///data.
        /// </summary>
        internal static string lblActualizar {
            get {
                return ResourceManager.GetString("lblActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add
        ///data.
        /// </summary>
        internal static string lblAgregar {
            get {
                return ResourceManager.GetString("lblAgregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adress gmail:.
        /// </summary>
        internal static string lblCorreo {
            get {
                return ResourceManager.GetString("lblCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by username,
        ///document number of
        ///gmail.
        /// </summary>
        internal static string lblDescripBuscar {
            get {
                return ResourceManager.GetString("lblDescripBuscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by name,
        ///number document
        ///or post.
        /// </summary>
        internal static string lblDescripBuscar2 {
            get {
                return ResourceManager.GetString("lblDescripBuscar2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete
        ///data.
        /// </summary>
        internal static string lblEliminar {
            get {
                return ResourceManager.GetString("lblEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State:.
        /// </summary>
        internal static string lblEstado {
            get {
                return ResourceManager.GetString("lblEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean
        ///fields.
        /// </summary>
        internal static string lblLimpiar {
            get {
                return ResourceManager.GetString("lblLimpiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General list of users.
        /// </summary>
        internal static string lblListadgvMostrar {
            get {
                return ResourceManager.GetString("lblListadgvMostrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of employees.
        /// </summary>
        internal static string lblListaempleados {
            get {
                return ResourceManager.GetString("lblListaempleados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of users.
        /// </summary>
        internal static string lblListaUsuarios {
            get {
                return ResourceManager.GetString("lblListaUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show
        ///data.
        /// </summary>
        internal static string lblMostrar {
            get {
                return ResourceManager.GetString("lblMostrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        internal static string lblNombre {
            get {
                return ResourceManager.GetString("lblNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee list number:.
        /// </summary>
        internal static string lblNumeroLista {
            get {
                return ResourceManager.GetString("lblNumeroLista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of user:.
        /// </summary>
        internal static string lblTipousuario {
            get {
                return ResourceManager.GetString("lblTipousuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload list.
        /// </summary>
        internal static string Recargar {
            get {
                return ResourceManager.GetString("Recargar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users form:.
        /// </summary>
        internal static string tlsFrm {
            get {
                return ResourceManager.GetString("tlsFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by username or document number.
        /// </summary>
        internal static string txtBuscar {
            get {
                return ResourceManager.GetString("txtBuscar", resourceCulture);
            }
        }
    }
}
