//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vista {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InglesPerros {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InglesPerros() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vista.InglesPerros", typeof(InglesPerros).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string btnBuscadorPacientes {
            get {
                return ResourceManager.GetString("btnBuscadorPacientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload list.
        /// </summary>
        internal static string btnRecargar {
            get {
                return ResourceManager.GetString("btnRecargar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload list.
        /// </summary>
        internal static string btnRecargarPacientes {
            get {
                return ResourceManager.GetString("btnRecargarPacientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        internal static string chkTraducirPerros {
            get {
                return ResourceManager.GetString("chkTraducirPerros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string grpAccionesPerros {
            get {
                return ResourceManager.GetString("grpAccionesPerros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data:.
        /// </summary>
        internal static string grpDatosPerros {
            get {
                return ResourceManager.GetString("grpDatosPerros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update
        ///data.
        /// </summary>
        internal static string lblActualizarPerros {
            get {
                return ResourceManager.GetString("lblActualizarPerros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add
        ///data.
        /// </summary>
        internal static string lblAgregarPerros {
            get {
                return ResourceManager.GetString("lblAgregarPerros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for name 
        ///name or document 
        ///owner´s.
        /// </summary>
        internal static string lblBuscarPerros {
            get {
                return ResourceManager.GetString("lblBuscarPerros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string lblBuscarPerrosBoton {
            get {
                return ResourceManager.GetString("lblBuscarPerrosBoton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string lblBuscarPropieBoton {
            get {
                return ResourceManager.GetString("lblBuscarPropieBoton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for name 
        ///or document.
        /// </summary>
        internal static string lblBuscarPropiePerros {
            get {
                return ResourceManager.GetString("lblBuscarPropiePerros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete
        ///data.
        /// </summary>
        internal static string lblEliminarPerros {
            get {
                return ResourceManager.GetString("lblEliminarPerros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender:.
        /// </summary>
        internal static string lblGeneroPerros {
            get {
                return ResourceManager.GetString("lblGeneroPerros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean
        ///fields.
        /// </summary>
        internal static string lblLimpiarPerros {
            get {
                return ResourceManager.GetString("lblLimpiarPerros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General patients list.
        /// </summary>
        internal static string lblListadoPacientes {
            get {
                return ResourceManager.GetString("lblListadoPacientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient list.
        /// </summary>
        internal static string lblListPerrosDGV {
            get {
                return ResourceManager.GetString("lblListPerrosDGV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owners list.
        /// </summary>
        internal static string lblListPropieDGV {
            get {
                return ResourceManager.GetString("lblListPropieDGV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show
        ///data.
        /// </summary>
        internal static string lblMostrarPerros {
            get {
                return ResourceManager.GetString("lblMostrarPerros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth:.
        /// </summary>
        internal static string lblnacimientoPerros {
            get {
                return ResourceManager.GetString("lblnacimientoPerros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string lblNombresPerros {
            get {
                return ResourceManager.GetString("lblNombresPerros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner list number:.
        /// </summary>
        internal static string lblNumListaPerros {
            get {
                return ResourceManager.GetString("lblNumListaPerros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight:.
        /// </summary>
        internal static string lblPesoPerros {
            get {
                return ResourceManager.GetString("lblPesoPerros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breed:.
        /// </summary>
        internal static string lblRazaPerros {
            get {
                return ResourceManager.GetString("lblRazaPerros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload
        ///list.
        /// </summary>
        internal static string lblRecargarPerrosBoton {
            get {
                return ResourceManager.GetString("lblRecargarPerrosBoton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload
        ///list.
        /// </summary>
        internal static string lblRecargarPropieBoton {
            get {
                return ResourceManager.GetString("lblRecargarPropieBoton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size:.
        /// </summary>
        internal static string lblTamañoPerros {
            get {
                return ResourceManager.GetString("lblTamañoPerros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patients for form:.
        /// </summary>
        internal static string tslFormPerros {
            get {
                return ResourceManager.GetString("tslFormPerros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for name or document owner´s.
        /// </summary>
        internal static string txtBuscarPaciente {
            get {
                return ResourceManager.GetString("txtBuscarPaciente", resourceCulture);
            }
        }
    }
}
