//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vista {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InglesEmpleados {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InglesEmpleados() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vista.InglesEmpleados", typeof(InglesEmpleados).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string btnBuscadorEmpleado {
            get {
                return ResourceManager.GetString("btnBuscadorEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reloading list.
        /// </summary>
        internal static string btnRecargarEmpleado {
            get {
                return ResourceManager.GetString("btnRecargarEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register contacts.
        /// </summary>
        internal static string chkContactosEmp {
            get {
                return ResourceManager.GetString("chkContactosEmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        internal static string chkTraducirEmpleado {
            get {
                return ResourceManager.GetString("chkTraducirEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string grpAccionesEmp {
            get {
                return ResourceManager.GetString("grpAccionesEmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact:.
        /// </summary>
        internal static string grpContactoEmp {
            get {
                return ResourceManager.GetString("grpContactoEmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data:.
        /// </summary>
        internal static string grpDatosEmp {
            get {
                return ResourceManager.GetString("grpDatosEmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update
        ///data.
        /// </summary>
        internal static string lblActualizarEmp {
            get {
                return ResourceManager.GetString("lblActualizarEmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update
        ///contact.
        /// </summary>
        internal static string lblActualizarTelEmp {
            get {
                return ResourceManager.GetString("lblActualizarTelEmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add
        ///data.
        /// </summary>
        internal static string lblAgregarEmp {
            get {
                return ResourceManager.GetString("lblAgregarEmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add
        ///contact.
        /// </summary>
        internal static string lblAgregarTelEmp {
            get {
                return ResourceManager.GetString("lblAgregarTelEmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name:.
        /// </summary>
        internal static string lblApellidosEmp {
            get {
                return ResourceManager.GetString("lblApellidosEmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for name,
        ///document o work position.
        /// </summary>
        internal static string lblBuscarEmp {
            get {
                return ResourceManager.GetString("lblBuscarEmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string lblBuscarEmpBoton {
            get {
                return ResourceManager.GetString("lblBuscarEmpBoton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work position:.
        /// </summary>
        internal static string lblCargoEmp {
            get {
                return ResourceManager.GetString("lblCargoEmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departament:.
        /// </summary>
        internal static string lblDepartamentoEmp {
            get {
                return ResourceManager.GetString("lblDepartamentoEmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete
        ///data.
        /// </summary>
        internal static string lblEliminarEmp {
            get {
                return ResourceManager.GetString("lblEliminarEmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean
        ///fields.
        /// </summary>
        internal static string lblLimpiarEmp {
            get {
                return ResourceManager.GetString("lblLimpiarEmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General employees list.
        /// </summary>
        internal static string lblListadoEmpleado {
            get {
                return ResourceManager.GetString("lblListadoEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees list.
        /// </summary>
        internal static string lblListEmpDGV {
            get {
                return ResourceManager.GetString("lblListEmpDGV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of employees with registered phone.
        /// </summary>
        internal static string lblListTelEmpDGV {
            get {
                return ResourceManager.GetString("lblListTelEmpDGV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show
        ///data.
        /// </summary>
        internal static string lblMostrarEmp {
            get {
                return ResourceManager.GetString("lblMostrarEmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipality:.
        /// </summary>
        internal static string lblMunicipioEmp {
            get {
                return ResourceManager.GetString("lblMunicipioEmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth:.
        /// </summary>
        internal static string lblnacimientoEmp {
            get {
                return ResourceManager.GetString("lblnacimientoEmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string lblNombresEmp {
            get {
                return ResourceManager.GetString("lblNombresEmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of document:.
        /// </summary>
        internal static string lblNumDocEmp {
            get {
                return ResourceManager.GetString("lblNumDocEmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of contact:.
        /// </summary>
        internal static string lblNumTelefonoEmp {
            get {
                return ResourceManager.GetString("lblNumTelefonoEmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload list.
        /// </summary>
        internal static string lblRecargarEmpBoton {
            get {
                return ResourceManager.GetString("lblRecargarEmpBoton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of document:.
        /// </summary>
        internal static string lblTipoDocumentoEmp {
            get {
                return ResourceManager.GetString("lblTipoDocumentoEmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees for form:.
        /// </summary>
        internal static string tslFormEmp {
            get {
                return ResourceManager.GetString("tslFormEmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for name, document or work position.
        /// </summary>
        internal static string txtBuscarEmpleado {
            get {
                return ResourceManager.GetString("txtBuscarEmpleado", resourceCulture);
            }
        }
    }
}
