//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vista {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InglesFactura {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InglesFactura() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vista.InglesFactura", typeof(InglesFactura).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string btnBuscarFactura {
            get {
                return ResourceManager.GetString("btnBuscarFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload list.
        /// </summary>
        internal static string btnRecargar {
            get {
                return ResourceManager.GetString("btnRecargar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reloading list.
        /// </summary>
        internal static string btnRecargarFactura {
            get {
                return ResourceManager.GetString("btnRecargarFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        internal static string chkTraducirFactura {
            get {
                return ResourceManager.GetString("chkTraducirFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string grbAccionesFactura {
            get {
                return ResourceManager.GetString("grbAccionesFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice data:.
        /// </summary>
        internal static string grbDatosFactura {
            get {
                return ResourceManager.GetString("grbDatosFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update
        ///data.
        /// </summary>
        internal static string lblActualizarFact {
            get {
                return ResourceManager.GetString("lblActualizarFact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add
        ///data.
        /// </summary>
        internal static string lblAgregarFact {
            get {
                return ResourceManager.GetString("lblAgregarFact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string lblBuscarFactBoton {
            get {
                return ResourceManager.GetString("lblBuscarFactBoton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for 
        ///document
        ///of owners,
        ///date or invoice
        ///status.
        /// </summary>
        internal static string lblBuscarFactura {
            get {
                return ResourceManager.GetString("lblBuscarFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for name
        ///or document.
        /// </summary>
        internal static string lblBuscarUsuarioPropie {
            get {
                return ResourceManager.GetString("lblBuscarUsuarioPropie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string lblBuscarUsuPropieBoton {
            get {
                return ResourceManager.GetString("lblBuscarUsuPropieBoton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete
        ///data.
        /// </summary>
        internal static string lblEliminarFact {
            get {
                return ResourceManager.GetString("lblEliminarFact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice status:.
        /// </summary>
        internal static string lblEstadoFactura {
            get {
                return ResourceManager.GetString("lblEstadoFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing date:.
        /// </summary>
        internal static string lblFechaFactura {
            get {
                return ResourceManager.GetString("lblFechaFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean
        ///fields.
        /// </summary>
        internal static string lblLimpiarFact {
            get {
                return ResourceManager.GetString("lblLimpiarFact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor list number :.
        /// </summary>
        internal static string lblListaDocFactura {
            get {
                return ResourceManager.GetString("lblListaDocFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General invoice list.
        /// </summary>
        internal static string lblListadoFactura {
            get {
                return ResourceManager.GetString("lblListadoFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner list number:.
        /// </summary>
        internal static string lblListaPropiFactura {
            get {
                return ResourceManager.GetString("lblListaPropiFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice list.
        /// </summary>
        internal static string lblListFacDGV {
            get {
                return ResourceManager.GetString("lblListFacDGV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owners list.
        /// </summary>
        internal static string lblListPropieDGV {
            get {
                return ResourceManager.GetString("lblListPropieDGV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User list.
        /// </summary>
        internal static string lblListUsuarioDGV {
            get {
                return ResourceManager.GetString("lblListUsuarioDGV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show
        ///data.
        /// </summary>
        internal static string lblMostrarFact {
            get {
                return ResourceManager.GetString("lblMostrarFact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload
        ///list.
        /// </summary>
        internal static string lblRecargarFactBoton {
            get {
                return ResourceManager.GetString("lblRecargarFactBoton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload
        ///list.
        /// </summary>
        internal static string lblRecargarUsuPropieBoton {
            get {
                return ResourceManager.GetString("lblRecargarUsuPropieBoton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total pay:.
        /// </summary>
        internal static string lblTotalFactura {
            get {
                return ResourceManager.GetString("lblTotalFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search employee.
        /// </summary>
        internal static string rbtnEmpleado {
            get {
                return ResourceManager.GetString("rbtnEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search owner.
        /// </summary>
        internal static string rbtnPropietario {
            get {
                return ResourceManager.GetString("rbtnPropietario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice form:.
        /// </summary>
        internal static string tslFormFactura {
            get {
                return ResourceManager.GetString("tslFormFactura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for document of owner&apos;s, date or status.
        /// </summary>
        internal static string txtBuscar {
            get {
                return ResourceManager.GetString("txtBuscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for document of
        ///owner&apos;s, date or status.
        /// </summary>
        internal static string txtBuscarPropieFactura {
            get {
                return ResourceManager.GetString("txtBuscarPropieFactura", resourceCulture);
            }
        }
    }
}
