//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vista {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InglesPropietarios {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InglesPropietarios() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vista.InglesPropietarios", typeof(InglesPropietarios).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Buscar {
            get {
                return ResourceManager.GetString("Buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrer contacts.
        /// </summary>
        internal static string chkContacto {
            get {
                return ResourceManager.GetString("chkContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact:.
        /// </summary>
        internal static string grpContacto {
            get {
                return ResourceManager.GetString("grpContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data:.
        /// </summary>
        internal static string grpDatos {
            get {
                return ResourceManager.GetString("grpDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update
        ///data.
        /// </summary>
        internal static string lblActualizar {
            get {
                return ResourceManager.GetString("lblActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update
        ///contact.
        /// </summary>
        internal static string lblActualizarcontacto {
            get {
                return ResourceManager.GetString("lblActualizarcontacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add
        ///data.
        /// </summary>
        internal static string lblAgregar {
            get {
                return ResourceManager.GetString("lblAgregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add
        ///contact.
        /// </summary>
        internal static string lblAgregarcontacto {
            get {
                return ResourceManager.GetString("lblAgregarcontacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last names:.
        /// </summary>
        internal static string lblApellidos {
            get {
                return ResourceManager.GetString("lblApellidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of contact:.
        /// </summary>
        internal static string lblContacto {
            get {
                return ResourceManager.GetString("lblContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to general list of contacts of owners.
        /// </summary>
        internal static string lblContactodgv {
            get {
                return ResourceManager.GetString("lblContactodgv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departament:.
        /// </summary>
        internal static string lblDepartamento {
            get {
                return ResourceManager.GetString("lblDepartamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by name
        ///or number of
        ///document.
        /// </summary>
        internal static string lbldescripbuscar {
            get {
                return ResourceManager.GetString("lbldescripbuscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by name, numer of
        ///document or contacts.
        /// </summary>
        internal static string lblDescripBuscarMostrar {
            get {
                return ResourceManager.GetString("lblDescripBuscarMostrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of owners with contact registred.
        /// </summary>
        internal static string lbldgvContacto {
            get {
                return ResourceManager.GetString("lbldgvContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of owners.
        /// </summary>
        internal static string lbldgvPropietarios {
            get {
                return ResourceManager.GetString("lbldgvPropietarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete
        ///data.
        /// </summary>
        internal static string lblEliminar {
            get {
                return ResourceManager.GetString("lblEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State:.
        /// </summary>
        internal static string lblEstado {
            get {
                return ResourceManager.GetString("lblEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth:.
        /// </summary>
        internal static string lblFechaNacimiento {
            get {
                return ResourceManager.GetString("lblFechaNacimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear
        ///fields.
        /// </summary>
        internal static string lblLimpiar {
            get {
                return ResourceManager.GetString("lblLimpiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show
        ///data.
        /// </summary>
        internal static string lblMostrar {
            get {
                return ResourceManager.GetString("lblMostrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipality:.
        /// </summary>
        internal static string lblMunicipio {
            get {
                return ResourceManager.GetString("lblMunicipio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Names:.
        /// </summary>
        internal static string lblNombres {
            get {
                return ResourceManager.GetString("lblNombres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of document:.
        /// </summary>
        internal static string lblNumDocumento {
            get {
                return ResourceManager.GetString("lblNumDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to general list of owners.
        /// </summary>
        internal static string lblPropietariosdgv {
            get {
                return ResourceManager.GetString("lblPropietariosdgv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of document:.
        /// </summary>
        internal static string lblTipoDocumento {
            get {
                return ResourceManager.GetString("lblTipoDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reloading list.
        /// </summary>
        internal static string Recargar {
            get {
                return ResourceManager.GetString("Recargar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owners form:.
        /// </summary>
        internal static string tlsFrm {
            get {
                return ResourceManager.GetString("tlsFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by name or number of document.
        /// </summary>
        internal static string txtBuscar {
            get {
                return ResourceManager.GetString("txtBuscar", resourceCulture);
            }
        }
    }
}
