//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vista {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InglesConsulta {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InglesConsulta() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vista.InglesConsulta", typeof(InglesConsulta).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string btnBuscadorConsulta {
            get {
                return ResourceManager.GetString("btnBuscadorConsulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reloading list.
        /// </summary>
        internal static string btnRecargarConsulta {
            get {
                return ResourceManager.GetString("btnRecargarConsulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        internal static string chkTraducirConsulta {
            get {
                return ResourceManager.GetString("chkTraducirConsulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string grbAccionesConsulta {
            get {
                return ResourceManager.GetString("grbAccionesConsulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment data:.
        /// </summary>
        internal static string grbDatosConsulta {
            get {
                return ResourceManager.GetString("grbDatosConsulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update
        ///data.
        /// </summary>
        internal static string lblActualizarConsul {
            get {
                return ResourceManager.GetString("lblActualizarConsul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add
        ///data.
        /// </summary>
        internal static string lblAgregarConsul {
            get {
                return ResourceManager.GetString("lblAgregarConsul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for name 
        ///of patient,
        ///document, 
        ///date, diagnosis
        ///or recipe.
        /// </summary>
        internal static string lblBuscarConsul {
            get {
                return ResourceManager.GetString("lblBuscarConsul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string lblBuscarConsulBoton {
            get {
                return ResourceManager.GetString("lblBuscarConsulBoton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string lblBuscarPacienteBoton {
            get {
                return ResourceManager.GetString("lblBuscarPacienteBoton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for name 
        ///or document
        ///of patient.
        /// </summary>
        internal static string lblBuscarPacienteConsul {
            get {
                return ResourceManager.GetString("lblBuscarPacienteConsul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnosis:.
        /// </summary>
        internal static string lblDiagnosticoConsulta {
            get {
                return ResourceManager.GetString("lblDiagnosticoConsulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete
        ///data.
        /// </summary>
        internal static string lblEliminarConsul {
            get {
                return ResourceManager.GetString("lblEliminarConsul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment date:.
        /// </summary>
        internal static string lblFechaConsulta {
            get {
                return ResourceManager.GetString("lblFechaConsulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean
        ///fields.
        /// </summary>
        internal static string lblLimpiarConsul {
            get {
                return ResourceManager.GetString("lblLimpiarConsul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General appointment list.
        /// </summary>
        internal static string lblListadoConsulta {
            get {
                return ResourceManager.GetString("lblListadoConsulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dog list number:.
        /// </summary>
        internal static string lblListaPeConsulta {
            get {
                return ResourceManager.GetString("lblListaPeConsulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment list.
        /// </summary>
        internal static string lblListConsulDGV {
            get {
                return ResourceManager.GetString("lblListConsulDGV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient list.
        /// </summary>
        internal static string lblListPacienteDGV {
            get {
                return ResourceManager.GetString("lblListPacienteDGV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show
        ///data.
        /// </summary>
        internal static string lblMostrarConsul {
            get {
                return ResourceManager.GetString("lblMostrarConsul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload list.
        /// </summary>
        internal static string lblRecargarConsulBoton {
            get {
                return ResourceManager.GetString("lblRecargarConsulBoton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload
        ///list.
        /// </summary>
        internal static string lblRecargarPacienteBoton {
            get {
                return ResourceManager.GetString("lblRecargarPacienteBoton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe:.
        /// </summary>
        internal static string lblRecetaConsulta {
            get {
                return ResourceManager.GetString("lblRecetaConsulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treatment:.
        /// </summary>
        internal static string lblTratamientoConsulta {
            get {
                return ResourceManager.GetString("lblTratamientoConsulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form appointment:.
        /// </summary>
        internal static string tlsFrmConsulta {
            get {
                return ResourceManager.GetString("tlsFrmConsulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for patient&apos;s name, document, date, diagnosis or recipe.
        /// </summary>
        internal static string txtBuscarConsulta {
            get {
                return ResourceManager.GetString("txtBuscarConsulta", resourceCulture);
            }
        }
    }
}
