//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vista {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InglesRecupContraseña {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InglesRecupContraseña() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vista.InglesRecupContraseña", typeof(InglesRecupContraseña).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string btnCambiarClaveRestablecer {
            get {
                return ResourceManager.GetString("btnCambiarClaveRestablecer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable credentials.
        /// </summary>
        internal static string btnRecuperarUsuarioAdmin {
            get {
                return ResourceManager.GetString("btnRecuperarUsuarioAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify credentials.
        /// </summary>
        internal static string btnVerficarAdmin {
            get {
                return ResourceManager.GetString("btnVerficarAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        internal static string chkTraducirAdmin {
            get {
                return ResourceManager.GetString("chkTraducirAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        internal static string chkTraducirMet2 {
            get {
                return ResourceManager.GetString("chkTraducirMet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        internal static string chkTraducirMet3 {
            get {
                return ResourceManager.GetString("chkTraducirMet3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        internal static string chkTraducirMetodosRecup {
            get {
                return ResourceManager.GetString("chkTraducirMetodosRecup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        internal static string chkTraducirRestablecerContra {
            get {
                return ResourceManager.GetString("chkTraducirRestablecerContra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show password.
        /// </summary>
        internal static string ckbMostrarClaveRestablecer {
            get {
                return ResourceManager.GetString("ckbMostrarClaveRestablecer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator credentials.
        /// </summary>
        internal static string grbCredencialAdmin {
            get {
                return ResourceManager.GetString("grbCredencialAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentials.
        /// </summary>
        internal static string grbCredencialesMet2 {
            get {
                return ResourceManager.GetString("grbCredencialesMet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentials.
        /// </summary>
        internal static string grbCredencialesMet3 {
            get {
                return ResourceManager.GetString("grbCredencialesMet3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked user&apos;s credentials.
        /// </summary>
        internal static string grbCredencialUsuario {
            get {
                return ResourceManager.GetString("grbCredencialUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Passwords do not match *.
        /// </summary>
        internal static string lblAdvertenciaContra {
            get {
                return ResourceManager.GetString("lblAdvertenciaContra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string lblApellidosMet2 {
            get {
                return ResourceManager.GetString("lblApellidosMet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string lblApellidosMet3 {
            get {
                return ResourceManager.GetString("lblApellidosMet3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work position.
        /// </summary>
        internal static string lblCargo2Met2 {
            get {
                return ResourceManager.GetString("lblCargo2Met2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work position.
        /// </summary>
        internal static string lblCargoMet3 {
            get {
                return ResourceManager.GetString("lblCargoMet3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password:.
        /// </summary>
        internal static string lblConfirmacionContra {
            get {
                return ResourceManager.GetString("lblConfirmacionContra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password:.
        /// </summary>
        internal static string lblContraAntigua {
            get {
                return ResourceManager.GetString("lblContraAntigua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password:.
        /// </summary>
        internal static string lblContraNueva {
            get {
                return ResourceManager.GetString("lblContraNueva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator password:.
        /// </summary>
        internal static string lblContraseñaAdmin {
            get {
                return ResourceManager.GetString("lblContraseñaAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string lblCorreo2Met2 {
            get {
                return ResourceManager.GetString("lblCorreo2Met2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string lblCorreo2Met3 {
            get {
                return ResourceManager.GetString("lblCorreo2Met3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator email:.
        /// </summary>
        internal static string lblCorreoAdmin {
            get {
                return ResourceManager.GetString("lblCorreoAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string lblCorreoElecMet2 {
            get {
                return ResourceManager.GetString("lblCorreoElecMet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string lblCorreoMet3 {
            get {
                return ResourceManager.GetString("lblCorreoMet3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked user&apos;s email.
        /// </summary>
        internal static string lblCorreoUsuarioBloqueado {
            get {
                return ResourceManager.GetString("lblCorreoUsuarioBloqueado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked user document.
        /// </summary>
        internal static string lblDocumentoUsuarioBloqueado {
            get {
                return ResourceManager.GetString("lblDocumentoUsuarioBloqueado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send email.
        /// </summary>
        internal static string lblEnviarCorreoMet3 {
            get {
                return ResourceManager.GetString("lblEnviarCorreoMet3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string lblEstadoMet2 {
            get {
                return ResourceManager.GetString("lblEstadoMet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string lblEstadoMet3 {
            get {
                return ResourceManager.GetString("lblEstadoMet3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By administrator intervention:
        ///This method consists of the
        ///than a system administrator
        ///enter your credentials, enable them
        ///and then put the user&apos;s
        ///locked..
        /// </summary>
        internal static string lblmetodo1 {
            get {
                return ResourceManager.GetString("lblmetodo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By data verification:
        ///This method consists of the user
        ///blocked enter your credentials,
        ///if the system detects that there is
        ///user, it will show him the data of that
        ///user and have to verify if they are yours
        ///or not..
        /// </summary>
        internal static string lblmetodo2 {
            get {
                return ResourceManager.GetString("lblmetodo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By message to the mail:
        ///It consists of sending a message via email
        ///where the password will be sent to you by
        ///default..
        /// </summary>
        internal static string lblmetodo3 {
            get {
                return ResourceManager.GetString("lblmetodo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By administrator intervention: 
        ///This method consists of a system 
        ///Administrator entering their credentials 
        ///enabling them, and then putting
        ///those of the blocked user..
        /// </summary>
        internal static string lblMetodoAdminsitrador {
            get {
                return ResourceManager.GetString("lblMetodoAdminsitrador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By message to the mail:
        ///It consists of sending a message via email
        ///where the password will be sent to you by
        ///default.
        /// </summary>
        internal static string lblMetodoCorreo {
            get {
                return ResourceManager.GetString("lblMetodoCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By data verification:
        ///This method consists of the user
        ///blocked enter your credentials,
        ///if the system detects that there is
        ///user, it will show you the data of that
        ///user and you have to verify if they are yours
        ///or not..
        /// </summary>
        internal static string lblMetodoDatos {
            get {
                return ResourceManager.GetString("lblMetodoDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string lblNombreMet3 {
            get {
                return ResourceManager.GetString("lblNombreMet3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string lblNombresMet2 {
            get {
                return ResourceManager.GetString("lblNombresMet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        internal static string lblNombreUsuarioAdmin {
            get {
                return ResourceManager.GetString("lblNombreUsuarioAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blocked user name:.
        /// </summary>
        internal static string lblNombreUsuarioBloqueado {
            get {
                return ResourceManager.GetString("lblNombreUsuarioBloqueado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string lblNombreUsuMet3 {
            get {
                return ResourceManager.GetString("lblNombreUsuMet3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am not this user.
        /// </summary>
        internal static string lblNoUsuarioMet2 {
            get {
                return ResourceManager.GetString("lblNoUsuarioMet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am not this user.
        /// </summary>
        internal static string lblNoUsuarioMet3 {
            get {
                return ResourceManager.GetString("lblNoUsuarioMet3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document number.
        /// </summary>
        internal static string lblNumDoc2Met2 {
            get {
                return ResourceManager.GetString("lblNumDoc2Met2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document number.
        /// </summary>
        internal static string lblNumDocMet2 {
            get {
                return ResourceManager.GetString("lblNumDocMet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document number.
        /// </summary>
        internal static string lblNumDocMet3 {
            get {
                return ResourceManager.GetString("lblNumDocMet3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am not this user.
        /// </summary>
        internal static string lblSiUsuarioMet2 {
            get {
                return ResourceManager.GetString("lblSiUsuarioMet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type user:.
        /// </summary>
        internal static string lblTipoUserAdmin {
            get {
                return ResourceManager.GetString("lblTipoUserAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string lblUsuario2Met2 {
            get {
                return ResourceManager.GetString("lblUsuario2Met2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        internal static string lblUsuarioAdmin {
            get {
                return ResourceManager.GetString("lblUsuarioAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string lblUsuarioMet2 {
            get {
                return ResourceManager.GetString("lblUsuarioMet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string lblUsuarioMet3 {
            get {
                return ResourceManager.GetString("lblUsuarioMet3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify data.
        /// </summary>
        internal static string lblVerificarMet2 {
            get {
                return ResourceManager.GetString("lblVerificarMet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify data.
        /// </summary>
        internal static string lblVerificarMet3 {
            get {
                return ResourceManager.GetString("lblVerificarMet3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset form.
        /// </summary>
        internal static string llbFormRestablecerContra {
            get {
                return ResourceManager.GetString("llbFormRestablecerContra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator intervention.
        /// </summary>
        internal static string tslIntervencionAdmin {
            get {
                return ResourceManager.GetString("tslIntervencionAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password recovery methods.
        /// </summary>
        internal static string tslMetodosRecuperacion {
            get {
                return ResourceManager.GetString("tslMetodosRecuperacion", resourceCulture);
            }
        }
    }
}
