//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vista {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InglesExpediente {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InglesExpediente() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vista.InglesExpediente", typeof(InglesExpediente).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify files.
        /// </summary>
        internal static string chkModificarExp {
            get {
                return ResourceManager.GetString("chkModificarExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        internal static string chkTraducirExpediente {
            get {
                return ResourceManager.GetString("chkTraducirExpediente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        internal static string chkTraducirMainExpediente {
            get {
                return ResourceManager.GetString("chkTraducirMainExpediente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form to access the appointment file.
        /// </summary>
        internal static string lbl1 {
            get {
                return ResourceManager.GetString("lbl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment list number:.
        /// </summary>
        internal static string lbl2 {
            get {
                return ResourceManager.GetString("lbl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update
        ///data.
        /// </summary>
        internal static string lblActualizarrExp {
            get {
                return ResourceManager.GetString("lblActualizarrExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add
        ///data.
        /// </summary>
        internal static string lblAgregarExp {
            get {
                return ResourceManager.GetString("lblAgregarExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of the appointment:.
        /// </summary>
        internal static string lblDescripConsulExpe {
            get {
                return ResourceManager.GetString("lblDescripConsulExpe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete
        ///data.
        /// </summary>
        internal static string lblEliminarExp {
            get {
                return ResourceManager.GetString("lblEliminarExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment date:.
        /// </summary>
        internal static string lblFechaConsulExpe {
            get {
                return ResourceManager.GetString("lblFechaConsulExpe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patients list number:.
        /// </summary>
        internal static string lblListaPacienMainExpe {
            get {
                return ResourceManager.GetString("lblListaPacienMainExpe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form to access patient&apos;s file.
        /// </summary>
        internal static string lblMainExpe {
            get {
                return ResourceManager.GetString("lblMainExpe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to file.
        /// </summary>
        internal static string lklAccederExpediente {
            get {
                return ResourceManager.GetString("lklAccederExpediente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the list appointment and patients.
        /// </summary>
        internal static string lklMostrarMainExpe {
            get {
                return ResourceManager.GetString("lklMostrarMainExpe", resourceCulture);
            }
        }
    }
}
